name: Docker Image CI

on:
    push:
        tags:
            - "v*"

env:
    TAG_NAME: ${{ github.ref_name }}
    REPO_NAME: ${{ github.event.repository.name }}
    DOCKER_USER: ${{ github.actor }}
    DOCKER_PASS: ${{ secrets.GH_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Tag Name
              run: |
                  echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
                  echo "Tag name from github.ref_name: ${{ github.ref_name }}"

            - name: Docker login
              run: docker login -u $DOCKER_USER -p $DOCKER_PASS ghcr.io

            - name: Build
              run: docker build . --file Dockerfile --tag ghcr.io/$DOCKER_USER/$REPO_NAME:$TAG_NAME

            - name: Push
              run: docker push ghcr.io/$DOCKER_USER/$REPO_NAME:$TAG_NAME

            - name: Update Latest Tag
              run: |
                  docker tag ghcr.io/$DOCKER_USER/$REPO_NAME:$TAG_NAME ghcr.io/$DOCKER_USER/$REPO_NAME:latest
                  docker push ghcr.io/$DOCKER_USER/$REPO_NAME:latest
